### ISSUE TITLE
Feature Request: Ability to specify a variables.scss file

### ISSUE THREAD

**Issue by alexgoldstone** [wodka/gulp-slate#11]
The original Slate project lets the user override basic styling properties without replacing the entire SCSS by changing a variables.scss file [as noted here](https://github.com/tripit/slate/wiki/Custom-Slate-Themes).

The gulp-slate `app.scss` file imports Slate's variables.scss file so there is no way to override the variables.scss without replacing `app.scss` in its entirety.

It would be useful if gulp-slate provided an option to specify a variables.scss which would be used instead of the variables.scss files provided by the Slate project while still continuing to use the rest of the provided scss files.

**Comment by wodka** [comment]
I'm not sure I can do this :/ - do you know a way to inject sass variables from node?

as an easy workaround:

``` sass
// filename: my.scss
// define your variables
@import "node_modules/gulp-slate/src/app.scss"
```

and the pass the the my.scss file to the slate config

**Comment by alexgoldstone** [comment]
This doesn't work because the `gulp-slate` `app.scss` imports Slate's `_variables.scss` which overrides any variables set by `my.scss`.

The fix would be to stop `app.scss` importing Slate's `_variables.scss` if an alternative scss variables file is specified but I cannot see a trivial way to achieve this.

**Comment by wodka** [comment]
working on a solution right now :)

**Comment by wodka** [comment]
there is now a new property variables -> there you can define the path to any scss file to import
