### ISSUE TITLE
options.variables broken

### ISSUE THREAD

**Issue by alexgoldstone** [wodka/gulp-slate#15]
Relative paths for `options.variables` are broken.

For example:

```
variables: 'docs/variables.scss'
```

**Line 108 of your index.js file would need to be changed from:**

```
rawScss.push('@imports "'+opts.variables+'";');
```

**to:**

```
rawScss.push('@import "'+ROOT+'../../'+opts.variables+'";');
```

I have not however raised a pull request as I have discovered that `options.variables` itself cannot work even when imported correctly because Slate's own `screen.css.scss` file is importing its own variables with:

```
@import 'variables';
```

**This line would need to be removed from Slate's own `screen.css.scss` file for any variables to be usable. Any ideas for how this might be automated?**

**Comment by wodka** [comment]
I just created a pull request in the original slate repository - if all variables only set a default the overwriting should work.

for the change on line 108:

I think it would be better to use:

```
path.dirname(process.argv[1]);
```

this way it would always use the folder of the node script that was started (it could be different)
the check should also then include to only prepend this if it was a relative path.

could you do that?

**Comment by alexgoldstone** [comment]
`process.argv[1]` isn't correct. The above pull request works the way you suggested but uses `module.parent.filename` to obtain the path of the gulpfile.
