### ISSUE TITLE
EOL bug

### ISSUE THREAD

**Issue by miminno** [wodka/gulp-slate#8]
Doesn't work if markdown file uses windows style line endings "\r\n".

src\slate.js:68
        throw new Error('No markdown page settings found!');

**Comment by wodka** [comment]
should work with version 1.0.4, can you try?

**Comment by wodka** [comment]
:/ ok, that was a bad fix by me, changed it again, can you try with 1.0.5?

**Comment by miminno** [comment]
Yeah, that should do. Thanks.
